### ISSUE TITLE
很好 继续努力

### ISSUE THREAD

**Issue by tnwss** [lichongjia/EFI-ASRock-H81M#1]
已打赏

**Comment by lichongjia** [comment]
> 已打赏

这个机器在老家，我可能很长时间内不会更新了。有什么问题通过公众号可以加我。

**Comment by tnwss** [comment]
我现在是0.5.8&nbsp; 怎么升级到最新啊 ！请教 ！&nbsp;

用心相信美好的事情即将发生！——Tang


&nbsp;

**Comment by lichongjia** [comment]
oc无法直接替换升级，因为新版和旧版的配置文件无法直接兼容。







------------------ 原始邮件 ------------------
发件人: tnwss <notifications@github.com&gt;
发送时间: 2020年6月27日 19:11
收件人: lichongjia/EFI-ASRock-H81M <EFI-ASRock-H81M@noreply.github.com&gt;
抄送: 见风致 <lichongjia@vip.qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[lichongjia/EFI-ASRock-H81M] 很好 继续努力 (#1)





 我现在是0.5.8&amp;nbsp; 怎么升级到最新啊 ！请教 ！&amp;nbsp; 
 
 用心相信美好的事情即将发生！——Tang 
 
 
 &amp;nbsp;
